-- 1. Create transaction_items table (The snapshot of what was bought)
create table "public"."transaction_items" (
    "id" bigint generated by default as identity primary key,
    "transaction_id" bigint not null references public.transactions(id) on delete cascade,
    "product_id" bigint not null references public.products(id),
    "quantity" integer not null check (quantity > 0),
    "price_at_purchase" numeric(12,2) not null, -- Stores price at moment of purchase
    "created_at" timestamp with time zone default now()
);

alter table "public"."transaction_items" enable row level security;

-- 2. Create the Trigger Function to manage stock
create or replace function public.handle_stock_deduction()
returns trigger as $$
begin
    -- When a new item is added to a transaction (Checkout)
    if (TG_OP = 'INSERT') then
        update public.products
        set stock_quantity = stock_quantity - new.quantity
        where id = new.product_id;
        
        -- Optional: Fail if stock goes negative
        if exists (select 1 from public.products where id = new.product_id and stock_quantity < 0) then
            raise exception 'Insufficient stock for product id %', new.product_id;
        end if;
    end if;

    return new;
end;
$$ language plpgsql security definer;

-- 3. Attach Trigger to transaction_items
create trigger on_transaction_item_insert
    after insert on public.transaction_items
    for each row execute function public.handle_stock_deduction();