-- 1. Categories
create sequence "public"."categories_id_seq";

create table "public"."categories" (
    "id" integer not null default nextval('public.categories_id_seq'::regclass) primary key,
    "name" text not null unique,
    "description" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
);

-- 2. Products
create table "public"."products" (
    "id" bigint generated by default as identity primary key,
    "seller_id" uuid not null references public.seller(seller_id) on delete cascade,
    "category_id" integer references public.categories(id) on delete set null,
    "name" text not null,
    "description" text not null,
    "price" bigint not null check (price >= 0),
    "discount" real,
    "img_url" text,
    -- OPTIMIZATION: Changed numeric to integer for stock, unless you sell by weight
    "stock_quantity" integer not null default 0 check (stock_quantity >= 0), 
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone,
    -- OPTIMIZATION: Removed 'review' text column. Reviews should be a separate table (which you have).
    "review_summary" text 
);

alter table "public"."products" enable row level security;

-- 3. Store Products (Many-to-Many link if needed, though product->seller->store already links them)
create table "public"."store_products" (
    "store_id" bigint not null references public.stores(id) on delete cascade,
    "product_id" bigint not null references public.products(id) on delete cascade,
    "created_at" timestamp with time zone not null default now(),
    primary key ("store_id", "product_id")
);

alter table "public"."store_products" enable row level security;