-- Drop problematic extension if exists
drop extension if exists "pg_net";

-- 1. Create Users (Extends auth.users)
create table "public"."users" (
    "id" uuid not null references auth.users(id) on delete cascade,
    "username" text unique,
    "email_verified" boolean default false,
    "phone_verified" boolean default false,
    "first_name" text,
    "last_name" text,
    "phone_number" text,
    "profile_picture" text,
    "date_of_birth" date,
    "gender" text check (gender in ('male', 'female', 'other')),
    "role" text default 'buyer' check (role in ('buyer', 'seller', 'admin')),
    "balance" numeric(12,2) default 0.00,
    "seller_rating" numeric(2,1) default 0.0,
    "buyer_rating" numeric(2,1) default 0.0,
    "status" text default 'active' check (status in ('active', 'inactive', 'suspended')),
    "last_login" timestamp with time zone,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    primary key ("id")
);

alter table "public"."users" enable row level security;

-- 2. User Addresses
create sequence "public"."user_addresses_id_seq";

create table "public"."user_addresses" (
    "id" bigint not null default nextval('public.user_addresses_id_seq'::regclass) primary key,
    "user_id" uuid references public.users(id) on delete cascade,
    "label" text,
    "recipient_name" text,
    "phone_number" text,
    "street" text,
    "city" text,
    "province" text,
    "postal_code" text,
    "country" text default 'Indonesia',
    "is_default" boolean default false,
    "created_at" timestamp with time zone default now()
);

alter table "public"."user_addresses" enable row level security;

-- 3. Stores (Removed products_id as it violates normalization)
create table "public"."stores" (
    "id" bigint generated by default as identity primary key,
    "store_name" text not null unique,
    "description" text,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."stores" enable row level security;

-- 4. Sellers (Links User to Store)
create table "public"."seller" (
    "seller_id" uuid not null primary key references public.users(id) on delete cascade,
    "store_id" bigint references public.stores(id) on delete cascade,
    "nik" text not null unique check (length(nik) <= 16),
    "ktp_url" text not null,
    "created_at" timestamp with time zone not null default now()
);

alter table "public"."seller" enable row level security;